### ISSUE TITLE
Jitpack dependency broken?

### ISSUE THREAD

**Issue by SebNickel** [jaytaylor/jaws#1]
This is the first time I've used jitpack, so perhaps I'm missing something obvious.

When I try importing jaws via my pom.xml exactly as described in the README, the jar downloaded into my local Maven repo contains just a skeleton:

    $ jar tf .m2/repository/com/github/jaytaylor/jaws/1.3/jaws-1.3.jar
    META-INF/
    META-INF/MANIFEST.MF
    META-INF/maven/
    META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/
    META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/jaws/
    META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/jaws/pom.xml
    META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/jaws/pom.properties

Whereas if, in my pom.xml, I indicate the latest commit hash instead of the release tag as the version, it works fine.

To investigate, I've forked the repo and created a new release (1.3.1) without modifying the code at all: [https://github.com/SebNickel/jaws/releases](https://github.com/SebNickel/jaws/releases)

When using that in my pom.xml, again, it works fine.
I.e.

    <dependency>
            <groupId>com.github.sebnickel</groupId>
            <artifactId>jaws</artifactId>
            <version>1.3.1</version>
    </dependency>

So does this mean that the jar cached on jitpack is broken? If so, I guess you should delete it.

It doesn't make sense to create a pull request if my understanding of the issue is at all correct. Pls let me know when you fix this and I'll delete my fork and update my Maven dependencies.

**Comment by jaytaylor** [comment]
@SebNickel Sorry to hear you've hit this issue.  I just verified and completely agree that the present jar at jitpack is useless.  *smh* :)

I'm not immediately sure how to get this fixed, will look into it more.  If you can shed any light, that would also be helpful and appreciated!

**Comment by jaytaylor** [comment]
SebNickel Sorry to hear you've hit this issue.  I just verified it and completely agree that the present jar at jitpack is useless.

*SMH*

:)

```(shell)
$ mvn \
    dependency:get \
    -DremoteRepositories=https://jitpack.io \
    -Ddest=. \
    -Dartifact=com.github.jaytaylor:jaws:1.3
# ...
$ unzip -l jaws-1.3.jar
Archive:  jaws-1.3.jar
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  07-31-16 18:33   META-INF/
      133  07-31-16 18:33   META-INF/MANIFEST.MF
        0  07-31-16 18:33   META-INF/maven/
        0  07-31-16 18:33   META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/
        0  07-31-16 18:33   META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/jaws/
     1417  07-31-16 18:32   META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/jaws/pom.xml
      120  07-31-16 18:33   META-INF/maven/eu.vitaliy.edu.smu.tspell.wordnet/jaws/pom.properties
 --------                   -------
     1670                   7 files
```

I'm not immediately sure how to get this fixed, will have to look into it more.  If you can shed any light or have any ideas, that'd also be helpful and appreciated!

**Comment by jaytaylor** [comment]
@SebNickel I've reached out to jitpack via email, we'll see what they recommend.

**Comment by SebNickel** [comment]
Thanks @jaytaylor :)
The jitpack docu says this under "Building->Rebuilding":

> You can remove builds that didn’t succeed if you Sign In on JitPack.io and look up your repository. Requesting them again will result in the project being rebuilt.

Still, it would be good to find out what happened. The build.log indicates that the original build was successful.

**Comment by SebNickel** [comment]
Off topic: Unless I've missed it, your code doesn't come with a license. Evidently you're fine with people using and changing your code (correct me if I'm wrong), so could you add a permissive license?

**Comment by jaytaylor** [comment]
@SebNickel Apparently the old release was pinned to the wrong commit, so I've pushed a new release (v1.3.1).  This should resolve the issue!

As for the license, I am not the original author.  Pretty sure Brett Spell is happy to share with others, but there was no explicit LICENSE.  I've added an explanation/disclosure to the top of the README, let me know if you think there is more we can do.

Cheers,
Jay

**Comment by jaytaylor** [comment]
Also- please feel free to close this if you feel your issue is resolved.  Thanks!

**Comment by SebNickel** [comment]
Excellent, thank you! I've just tested it and can confirm that it works.

If you can get Brett Spell's permission to add a license, that could indeed be helpful.

**Comment by jaytaylor** [comment]
I will try shooting him an email.

**Comment by jaytaylor** [comment]
@SebNickel Brett Spell got back to me and we now have a permissive BSD license in-place!  Thanks again for your collaboration on this.

**Comment by SebNickel** [comment]
Awesome! :)
Happy I could be of help, @jaytaylor. Thank you for your responsiveness, and for the code!

**Comment by SebNickel** [comment]
The README still says "There was no license included or referenced anywhere that I found." with no further comments. That may be confusing. Maybe delete that line from the README?

**Comment by jaytaylor** [comment]
Great catch- fixed!
